name: loqmtk_food_delivery_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash/
    - assets/images/banner/
    - assets/images/details/
    - assets/images/details/side_options/
    - assets/images/details/toppings/
    - assets/icons/
    - assets/images/logo/
    - assets/images/
    - assets/images/cart/
    - assets/images/payment/
  fonts:
    - family: Gagalin
      fonts:
        - asset: assets/fonts/Gagalin-Regular.otf
    - family: Luckiest Guy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
    - family: ReemKufi
      fonts:
        - asset: assets/fonts/ReemKufi-Regular.ttf
